import React from "react";
import {
  Box,
  Typography,
  Button,
  Card,
  CardContent,
} from "@mui/material";
import { useNavigate } from "react-router-dom";
import { FaLungs, FaBrain, FaHeart, FaRobot } from "react-icons/fa";
import { motion } from "framer-motion";

export default function MeditationContent() {
  const navigate = useNavigate();

  const cardData = [
    {
      icon: <FaLungs size={32} color="#fff" />,
      title: "Breathing Exercises",
      description:
        "Try the 4-7-8 technique: Inhale for 4 sec, hold for 7 sec, exhale for 8 sec.",
      buttonText: "Start Exercise",
      route: "/breathing-exercise",
      gradient: "linear-gradient(135deg, #6a82fb, #fc5c7d)",
    },
    {
      icon: <FaBrain size={32} color="#fff" />,
      title: "Guided Meditation",
      description:
        "Listen to short guided sessions to calm your mind and body.",
      buttonText: "Start Meditation",
      route: "/guided-meditation",
      gradient: "linear-gradient(135deg, #5C6BC0, #8E24AA)",
    },
    {
      icon: <FaHeart size={32} color="#fff" />,
      title: "Coping Strategies",
      description:
        "Personalized mental health tips to boost emotional resilience.",
      buttonText: "Explore Strategies",
      route: "/coping-strategies",
      gradient: "linear-gradient(135deg, #00c6ff, #0072ff)",
    },
    {
      icon: <FaRobot size={32} color="#fff" />,
      title: "Chatbot Suggestions",
      description:
        "Explore personalized suggestions generated by our AI-powered chatbot.",
      buttonText: "Explore Suggestions",
      route: "/chatbot-suggestions",
      gradient: "linear-gradient(135deg, #00bfae, #1f8c8c)",
    },
  ];

  return (
    <Box
      sx={{
        width: "100%",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        pt: 6,
        px: 3,
        background: "linear-gradient(to bottom, #297194, #D1E1F7, #E7F2F7)",
      }}
    >
      <motion.div
        initial={{ opacity: 0, y: -30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: "easeInOut" }}
      >
        <Typography
          variant="h4"
          fontWeight="bold"
          sx={{
            mb: 5,
            textAlign: "center",
            fontFamily: "Poppins, sans-serif",
            color: "#fff", // White title text
          }}
        >
          Meditation & Coping Mechanisms
        </Typography>
      </motion.div>

      <Box
  sx={{
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 4,
    width: "100%",
    maxWidth: "1000px",
    alignItems: "stretch", // Make all cards same height
  }}
>
  {cardData.map((item, index) => (
    <motion.div
      key={index}
      initial={{ opacity: 0, scale: 0.7 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{
        delay: index * 0.4,
        duration: 0.8,
        type: "spring",
        stiffness: 200,
      }}
    >
      <Card
        sx={{
          height: "100%", // Card stretches to match grid cell
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          backdropFilter: "blur(15px)",
          background: item.gradient,
          borderRadius: "20px",
          boxShadow: "0 12px 30px rgba(0, 0, 0, 0.1)",
          color: "white",
          transition: "all 0.3s ease-in-out",
          "&:hover": {
            transform: "scale(1.1) rotate(6deg) translateY(-8px)",
            boxShadow: "0 18px 50px rgba(0, 0, 0, 0.2)",
            background: "linear-gradient(135deg, #3a2f60, #b96ed1)",
            transition: "all 0.4s ease-out",
          },
        }}
      >
        <CardContent
          sx={{
            height: "100%", // Fill card vertically
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "space-between",
            textAlign: "center",
            p: 3,
          }}
        >
          <Box
            sx={{
              width: 64,
              height: 64,
              borderRadius: "50%",
              backgroundColor: "rgba(255, 255, 255, 0.3)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              mb: 2,
              transition: "all 0.3s ease",
              "&:hover": {
                transform: "scale(1.2)",
                backgroundColor: "rgba(255, 255, 255, 0.5)",
              },
            }}
          >
            {item.icon}
          </Box>
          <Typography variant="h6" fontWeight="bold" sx={{ mb: 1 }}>
            {item.title}
          </Typography>
          <Typography
            variant="body2"
            sx={{ mb: 3, fontSize: "0.95rem", lineHeight: 1.6 }}
          >
            {item.description}
          </Typography>
          <Button
            variant="contained"
            sx={{
              backgroundColor: "#ffffff",
              color: "#333",
              textTransform: "none",
              fontWeight: "bold",
              borderRadius: "10px",
              px: 3,
              py: 1,
              boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
              transition: "all 0.3s ease-in-out",
              "&:hover": {
                backgroundColor: "#e5e5e5",
                transform: "scale(1.1)",
                boxShadow: "0 8px 16px rgba(0, 0, 0, 0.15)",
              },
            }}
            onClick={() => navigate(item.route)}
          >
            {item.buttonText}
          </Button>
        </CardContent>
      </Card>
    </motion.div>
  ))}
</Box>

    </Box>
  );
}
